import Counter from "@/app/_components/Counter";
import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/Navigation";

import "@/app/_styles/globals.css";
import Header from "./_components/Header";
import ReservationProvider from "./_lib/useReservation";
import { Josefin_Sans } from 'next/font/google'

const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: "swap",
})


export const metadata = {
  title: {
    template: "%s The wild Oasis",
    default: "Welcome : The wild Oasis",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 text-slate-200 ${josefin.className}`} >
        <Header />
        <main>
          <ReservationProvider>
            {children}
          </ReservationProvider>
        </main>
      </body>
    </html>
  );
}
